/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { AjunaERC20 } from "./AjunaERC20";
export type { AjunaWrapper } from "./AjunaWrapper";
